name: CI/CD Pipeline for FinanciaCore

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:14
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: financiacore
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U user -d financiacore"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      # Run tests
      - name: Run tests
        env:
          DB_ENGINE: postgresql
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: financiacore
          DB_USER: user
          DB_PASSWORD: password
        run: |
          pytest --cov=src tests/

  docker-build:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build production Docker image
      - name: Build production image
        run: |
          docker build -f docker/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/financiacore:latest .

      # Build development Docker image
      - name: Build development image
        run: |
          docker build -f docker/Dockerfile.dev -t ${{ secrets.DOCKER_USERNAME }}/financiacore-dev:latest .

      # Push Docker images
      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/financiacore:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/financiacore-dev:latest

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: docker-build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: SSH to Production Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}
          port: ${{ secrets.PROD_SERVER_PORT }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/financiacore:latest
            docker stop financiacore || true
            docker rm financiacore || true
            docker run -d --name financiacore \
              -p 8000:8000 \
              --env-file .env \
              ${{ secrets.DOCKER_USERNAME }}/financiacore:latest
