name: CI/CD Pipeline for FinanciaCore (Development)

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    name: Build and Test (Development)
    runs-on: ubuntu-latest

    steps:
      # Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Loguearse en DockerHub (opcional si necesitas subir imágenes)
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construir imagen de desarrollo
      - name: Build development Docker image
        run: |
          docker build -f docker/Dockerfile.dev -t financiacore-dev:latest .

      # Ejecutar pruebas en Docker Compose
      - name: Run tests using Docker Compose
        run: |
          docker-compose -f docker-compose.dev.yml up --build -d
          docker-compose -f docker-compose.dev.yml exec app pytest --cov=src tests/
          docker-compose -f docker-compose.dev.yml down
