name: CI/CD Pipeline for FinanciaCore (Producción)

on:
  push:
    branches:
      - main  # Solo para la rama de producción

jobs:
  build-production-image:
    name: Build and Test Docker Image (Producción)
    runs-on: ubuntu-latest

    steps:
      # Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Loguearse en DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construir la imagen de producción
      - name: Build production Docker image
        run: |
          docker build -f docker/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/financiacore:latest .

      # Testear el contenedor de producción
      - name: Test production Docker container
        run: |
          docker network create financiacore-network || true
          docker run -d --name db --network financiacore-network \
            -e POSTGRES_USER=prod_user \
            -e POSTGRES_PASSWORD=prod_password \
            -e POSTGRES_DB=financiacore \
            postgres:14
          docker run --rm --name financiacore --network financiacore-network \
            -e DB_ENGINE=postgresql \
            -e DB_HOST=db \
            -e DB_PORT=5432 \
            -e DB_NAME=financiacore \
            -e DB_USER=prod_user \
            -e DB_PASSWORD=prod_password \
            ${{ secrets.DOCKER_USERNAME }}/financiacore:latest pytest --cov=src tests/
          docker stop db && docker network rm financiacore-network

      # Publicar la imagen en DockerHub
      - name: Push production image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/financiacore:latest

  deploy:
    name: Deploy to Production Server
    runs-on: ubuntu-latest
    needs: build-production-image
    if: github.ref == 'refs/heads/main'

    steps:
      - name: SSH to Production Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}
          port: ${{ secrets.PROD_SERVER_PORT }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/financiacore:latest
            docker stop financiacore || true
            docker rm financiacore || true
            docker run -d --name financiacore \
              -p 8000:8000 \
              --env-file .env \
              ${{ secrets.DOCKER_USERNAME }}/financiacore:latest
